export const SET_CURRENCY = 'SET_CURRENCY'
export const CREATE_CLIENT = 'CREATE_CLIENT'
export const SET_SHOP = 'SET_SHOP'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_PRODUCT = 'SET_PRODUCT'
export const SET_PRODUCT_FILTER = 'SET_PRODUCT_FILTER'
export const CREATE_CHECKOUT = 'CREATE_CHECKOUT'
export const UPDATE_CHECKOUT = 'UPDATE_CHECKOUT'

