export const LOAD_SHOPIFY = 'LOAD_SHOPIFY'
export const LOAD_CHANNEL = 'LOAD_CHANNEL'
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL'
export const FINISH_LOAD = 'FINISH_LOAD'
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL'
export const UPDATE_CHECKOUT = 'UPDATE_CHECKOUT'
export const ADD_NOTE = 'ADD_NOTE'


