# Site settings
title: Cheetah Factory Racing
email: dev@ocupop.com
url: "https://snowy-slipper.cloudvent.net/"
permalink: pretty

# Social sharing
description: 'Snowmobile Racks, Accessories, Backcountry Snowboarding & Snowmobile Adventure Hub'
socialshare:
  featured_image: img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics:
  default:

# Collections
collections:
  elements:
    output: false
  team_members:
    output: false
  dealers:
    output: false
  homies:
    output: false
  products:
    output: true
  product_collections:
    output: true



defaults:
  - scope:
      type: "products"
    values:
      layout: product
      _options:
        image:
          uploads_dir: "uploads/products/"
  - scope:
      type: "posts"
    values:
      layout: post
      _options:
        featured_image:
          uploads_dir: "uploads/posts/"
  - scope:
      type: "dealers"
    values:
      _options:
        image:
          uploads_dir: "uploads/dealers/"
  - scope:
      type: "product_collections"
    values:
      _options:
        featured_image:
          uploads_dir: "uploads/product_collections/"        


# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss

# plugins:

# Cloudcannon Configuration
_array_structures:
  meta:
    - label: Meta Data
      icon: share
      value:
        description:
        image:
  faqs:
    - label: FAQ
      icon: question_answer
      value:
        question:
        answer_html:
  links:
    - label: Links
      icon: link
      value:
        url:
        label:
        screenshot_image:
        icon:
  gallery:
    - label: Image
      icon: insert_photo
      value:
        _type: image
        caption:
        thumbnail_image:
        image:
  assets:
    - label: Image
      icon: insert_photo
      value:
        _type: image
        title:
        image:
    - label: Video
      icon: videocam
      value:
        _type: video
        title:
        embed_url:
  wholesale:
    - label: Wholesale Data
      icon: share
      value:
        customer_level:
        price:

brands:
  - Yamaha
  - Polaris
  - Arctic Cat
  - Ski-Doo

_comments:
  brands: Select the brands this product is compatible with  
